replicaCount: 1

namespace: activemq-artemis-operator

image:
  repository: quay.io/artemiscloud/activemq-artemis-operator
  pullPolicy: IfNotPresent
  tag: "1.0.14"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "activemq-artemis-helm-chart"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Variables added from the previous comment
namespace_name: activemq-artemis-operator

install_script: activemq-artemis-operator/deploy/install_opr.sh

crd_yaml_paths:
  - activemq-artemis-operator/config/crs/broker_activemqartemis_cr.yaml
  - activemq-artemis-operator/config/crs/broker_activemqartemisaddress_cr.yaml
  - activemq-artemis-operator/config/crs/broker_activemqartemisscaledown_cr.yaml
  - activemq-artemis-operator/config/crs/broker_activemqartemissecurity_cr.yaml

operator_yaml_path: activemq-artemis-operator/deploy/operator.yaml

